import os
import time

print(" __   __   __              __  __   __    __       ___  __")     
print("/  \ |__) (_    |\ | \  / |_  |__) /     |__)  /\   |  /   |__|") 
print("\__/ |__) __)   | \|  \/  |   |__) \__   |    /--\  |  \__ |  |")                                                         
print(" ")
print("OBS NVFBC PATCH v1.0")
print("github.com/Liniuta/obs-nvfbc-patch")
print("Getting requiered variables and loading the program..")
print("Make sure you have OBS installed on your system!")
print(" ")
time.sleep(0.5)

def obs_patch():
    print("Starting...")
    print("#" * 30)
    print("Patching Nvidia driver...")
    print("#" * 30)
    time.sleep(2)
    os.system("git clone https://github.com/keylase/nvidia-patch")
    os.chdir("nvidia-patch/")
    os.system("sudo ./patch-fbc.sh")
    os.chdir("..")
    print("#" * 30)
    print("Building OBS module..")
    print("#" * 30)
    os.system("git clone https://gitlab.com/fzwoch/obs-nvfbc")
    os.chdir("obs-nvfbc/")
    os.system("meson build")
    os.system("ninja -C build")
    time.sleep(2)
    print("#" * 30)
    print("Adding to OBS..")
    print("#" * 30)
    os.chdir(f"/home/{username}/.config/obs-studio/")
    os.mkdir("plugins")
    os.chdir(f"/home/{username}/.config/obs-studio/plugins/")
    os.mkdir("nvfbc")
    os.chdir(f"/home/{username}/.config/obs-studio/plugins/nvfbc/")
    os.mkdir("bin")
    os.chdir(f"/home/{username}/.config/obs-studio/plugins/nvfbc/bin/")
    os.mkdir("64bit")
    os.chdir(working_directory)
    os.chdir("obs-nvfbc/build/")
    os.system(f"cp nvfbc.so /home/{username}/.config/obs-studio/plugins/nvfbc/bin/64bit/")                                                                         
    time.sleep(2)
    print(" ")
    print("Finished!")
    print("Now you can open OBS and add the new NVFBC source.")
    print("Enjoy!")
    print("#" * 30)
    print(" ")
    time.sleep(1)

username = os.getlogin()
working_directory = os.getcwd()
time.sleep(1.5)
print("What distro are you running?:")
print(" [1] Debian based (Ubuntu, Linux Mint, Pop!_OS, elementary OS, MX Linux, Zorin OS etc.)")
print(" [2] Arch based (Manjaro, EndeavourOS, Garuda Linux, Artix, Arco etc.) ")
print(" [3] Fedora")
print(" [4] openSUSE")
print(" [5] Solus")
print(" ")
distros = input("Enter the number of your distro: ")
if distros =="1":
    os.system("sudo apt install libgl-dev meson ninja-build")
    obs_patch()
elif distros == "2":
    os.system("sudo pacman -S libgl-dev meson ninja-build")
    obs_patch()
elif distros == "3":
    os.system("sudo dnf install libgl-dev meson ninja-build")
    obs_patch()
elif distros == "4":
    os.system("sudo zypper install libgl-dev meson ninja-build")
    obs_patch()
elif distros == "5":
    os.system("sudo eopkg install libgl-dev meson ninja-build")
    obs_patch()
else:
    print(" ")
    print("Please enter a valid number!")
